### PR TITLE
Implement passthrough

### PR DESCRIPTION
**Pull request by rusty-snake**

### CODE REVIEW

**Comment by topimiettinen** [comment]
I don't know. Firefox is not helped by libaslrmalloc because of the internal malloc implementation (which doesn't randomize).

**Comment by topimiettinen** [comment]
Loosely related to this PR:

The most flexible system for configuration would be to support reading profiles in sequence:
1. `/usr/lib/libaslrmalloc/*.profile` (distro)
2. `/etc/libaslrmalloc/*.profile` (local admin overriding the distro)
3. `~/.config/libaslrmalloc/*.profile` (user permanently overriding the admin, when allowed (not for SUID))
4. environment (user temporarily overriding 3., when allowed (not for SUID))

Even fancier would be to support drop-ins like systemd and some other software, but I think that's too fancy for the simple library.

Also there should be a default profile for all applications (also subject to 1.-3.). It could be a file with a special name which doesn't match `*.profile` (like `default.conf`), or the profiles could be pushed to a directory (`.../libaslrmalloc/profile/*.profile`) and the default profile could then be `.../libaslrmalloc/default.profile`.

@rusty-snake WDYT?

**Comment by topimiettinen** [comment]
Looks good to me. I don't know that much about meson to comment on your change, what's your preference?

**Comment by rusty-snake** [comment]
> I'm working on a hash table implementation to speed up free(), maybe that will help with performance.

If that's done, libaslrmalloc is ready for a tagged release IMHO.

> The most flexible system for configuration would be to support reading profiles in sequence:
> 
>     1. `/usr/lib/libaslrmalloc/*.profile` (distro)
> 
>     2. `/etc/libaslrmalloc/*.profile` (local admin overriding the distro)
> 
>     3. `~/.config/libaslrmalloc/*.profile` (user permanently overriding the admin, when allowed (not for SUID))
> 
>     4. environment (user temporarily overriding 3., when allowed (not for SUID))

:+1:

> Also there should be a default profile for all applications (also subject to 1.-3.). It could be a file with a special name which doesn't match `*.profile` (like `default.conf`), or the profiles could be pushed to a directory (`.../libaslrmalloc/profile/*.profile`) and the default profile could then be `.../libaslrmalloc/default.profile`.

Using `.../libaslrmalloc/profiles/*.profile` has the advantage that if we ever need a second kind of "profiles" we can just add a new subdir instead of a one dir cluttered with different files.

> Looks good to me. I don't know that much about meson to comment on your change, what's your preference?

You should always use `add_project_foo` unless you know that you need `add_global_foo`.
https://mesonbuild.com/Reference-manual_functions.html#add_global_link_arguments

**Comment by topimiettinen** [comment]
I think I found the problem!

**Comment by topimiettinen** [comment]
It seems that dlsym() can call calloc(): https://sourceware.org/git/?p=glibc.git;a=blob;f=elf/dl-lookup.c;h=430359af39332d139453e5765af37ad9fd51a63b;hb=HEAD#l271

Then, as `libc_calloc` is still NULL, segfault happens.

**Comment by topimiettinen** [comment]
Updated #15 with less ugly version.

**Pull request merged**
